@baseUrl = http://localhost:8000

GET http://localhost:8000/health
Accept: application/json

###

POST http://localhost:8000/jobs
Content-Type: application/json

{
  "type": "send_email",
  "payload": {
    "to": "mahi0518n@gmail.com",
    "subject": "Test from Queue",
    "body": "This email is sent asynchronously 🚀"
  }
}

###

GET http://localhost:8000/jobs
Accept: application/json

###
GET http://localhost:8000/jobs/528bf8bbba564ce7806579c2c9f41c22
Accept: application/json

###

GET http://localhost:8000/metrics
Accept: application/json

###

